/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        "thicboi-thin": ["ThicboiThin", "sans-serif"],
        "thicboi-light": ["ThicboiLight", "sans-serif"],
        "thicboi-regular": ["ThicboiRegular", "sans-serif"],
        "thicboi-medium": ["ThicboiMedium", "sans-serif"],
        "thicboi-semibold": ["ThicboiSemibold", "sans-serif"],
        "thicboi-bold": ["ThicboiBold", "sans-serif"],
        "thicboi-extrabold": ["ThicboiExtraBold", "sans-serif"],
        "thicboi-thicc": ["ThicboiThicc", "sans-serif"],
      },
      animation: {
        marquee: "marquee 25s ease-in-out infinite",
        marquee2: "marquee2 25s ease-in-out infinite",
        marqueeReverse: "marqueeReverse 25s ease-in-out infinite",
        marquee2Reverse: "marquee2Reverse 25s ease-in-out infinite",
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "10%": { transform: "translateX(-10%)" },
          "20%": { transform: "translateX(-20%)" },
          "30%": { transform: "translateX(-30%)" },
          "40%": { transform: "translateX(-40%)" },
          "50%": { transform: "translateX(-50%)" },
          "60%": { transform: "translateX(-60%)" },
          "70%": { transform: "translateX(-70%)" },
          "80%": { transform: "translateX(-80%)" },
          "90%": { transform: "translateX(-90%)" },
          "100%": { transform: "translateX(-100%)" },
        },
        marquee2: {
          "0%": { transform: "translateX(100%)" },
          "10%": { transform: "translateX(90%)" },
          "20%": { transform: "translateX(80%)" },
          "30%": { transform: "translateX(70%)" },
          "40%": { transform: "translateX(60%)" },
          "50%": { transform: "translateX(50%)" },
          "60%": { transform: "translateX(40%)" },
          "70%": { transform: "translateX(30%)" },
          "80%": { transform: "translateX(20%)" },
          "90%": { transform: "translateX(10%)" },
          "100%": { transform: "translateX(0%)" },
        },
        marqueeReverse: {
          "0%": { transform: "translateX(-100%)" },
          "10%": { transform: "translateX(-90%)" },
          "20%": { transform: "translateX(-80%)" },
          "30%": { transform: "translateX(-70%)" },
          "40%": { transform: "translateX(-60%)" },
          "50%": { transform: "translateX(-50%)" },
          "60%": { transform: "translateX(-40%)" },
          "70%": { transform: "translateX(-30%)" },
          "80%": { transform: "translateX(-20%)" },
          "90%": { transform: "translateX(-10%)" },
          "100%": { transform: "translateX(0%)" },
        },
        marquee2Reverse: {
          "0%": { transform: "translateX(0%)" },
          "10%": { transform: "translateX(10%)" },
          "20%": { transform: "translateX(20%)" },
          "30%": { transform: "translateX(30%)" },
          "40%": { transform: "translateX(40%)" },
          "50%": { transform: "translateX(50%)" },
          "60%": { transform: "translateX(60%)" },
          "70%": { transform: "translateX(70%)" },
          "80%": { transform: "translateX(80%)" },
          "90%": { transform: "translateX(90%)" },
          "100%": { transform: "translateX(100%)" },
        },
      },
    },
  },
  plugins: [],
};
